### ISSUE TITLE
VSCode as a ROS2 development environment

### ISSUE THREAD

**Issue by JaehyunShim** [christophebedard/dotfiles#3]
Hi, 

I saw [this file](https://github.com/christophebedard/dotfiles/blob/master/config/vscode_settings.json) and wondered if you are using VSCode when you are working on ROS2 projects. I was trying to build my packages in VSCode so I could track those APIs from /opt/ros/distro by pressing the F12 key but I couldn't. Do you know how to? 

Any advice would be appreciated,
Jaehyun

**Comment by christophebedard** [comment]
You might want to take a look at the ROS VSCode extension: https://github.com/ms-iot/vscode-ros

I personally don't really build using VSCode + I build all of ROS 2 from source, so I don't use `/opt/ros/...`.

**Comment by JaehyunShim** [comment]
Thank you for your answer.
